ALTER PROCEDURE APR_GET_TBOM
(
	IN ITEMCODE	NVARCHAR(20),
	IN QUANTITY INT
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
	DECLARE GRPCODE NVARCHAR(10) ARRAY;
	DECLARE GRPQTY INT ARRAY;
	DECLARE GRPMAX INT;
	DECLARE GRPCODETEMP NVARCHAR(10);
	DECLARE i INT;
	
	-- 골고루 관리에 등록된 그룹코드 개수 카운트
	SELECT
		COUNT("U_GRPCODE")
	INTO GRPMAX
	FROM "@APR_TMP1"
	WHERE "Code" = :ITEMCODE;
	
	-- 그룹코드를 배열 GRPCODE에 담기
	i := 1;
	FOR i IN 1..GRPMAX DO
		SELECT
			"U_GRPCODE"
		INTO GRPCODETEMP
		FROM "@APR_TMP1"
		WHERE "Code" = :ITEMCODE
		AND "LineId" = :i;
		
		GRPCODE[:i] := GRPCODETEMP;
	END FOR;
	
	-- 배열 GRPCODE의 길이만큼 반복
	i := 1;
	FOR i IN 1..CARDINALITY(:GRPCODE) DO
		SELECT :GRPCODE[:i] FROM DUMMY;
	END FOR;
END;
CALL APR_GET_TBOM ('S212', 1);