DROP PROCEDURE APR_PAB0901;
CREATE PROCEDURE APR_PAB0901(
	IN MON NVARCHAR(10),
	IN EMPNO NVARCHAR(20)
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
	
	DECLARE ROWCNT INT;
	DECLARE X INT;
	DECLARE Y INT;
	DECLARE Z INT;
	DECLARE I INT;

	CREATE LOCAL TEMPORARY TABLE #TMP1(
		SEQ INT,
		TMP1STR NVARCHAR(20),
		TMP1VAL INT
	);
	CREATE LOCAL TEMPORARY TABLE #TMP2(
		SEQ INT,
		TMP2STR NVARCHAR(20),
		TMP2VAL INT
	);
	CREATE LOCAL TEMPORARY TABLE #TMP3(
		SEQ INT,
		TMP3STR NVARCHAR(20),
		TMP3VAL INT
	);
	
	INSERT INTO #TMP1
	SELECT
		RANK() OVER(ORDER BY PRT_SEQ),
		C.PAY_NM,
		B.PAY_AMT
	FROM APR_PAB150 B
	LEFT JOIN APR_PAZ300 C ON B.PAY_CD = C.PAY_CD
	WHERE (B.EMP_NO = :EMPNO OR :EMPNO = '')
	AND (B.PAY_MON = :MON OR :MON = '')
	AND C.PD_BC = 'PA112100';
	
	INSERT INTO #TMP2
	SELECT
		RANK() OVER(ORDER BY PRT_SEQ),
		C.PAY_NM,
		B.PAY_AMT
	FROM APR_PAB150 B
	LEFT JOIN APR_PAZ300 C ON B.PAY_CD = C.PAY_CD
	WHERE (B.EMP_NO = :EMPNO OR :EMPNO = '')
	AND (B.PAY_MON = :MON OR :MON = '')
	AND C.PD_BC = 'PA112200';
	
	INSERT INTO #TMP3
	SELECT
		RANK() OVER(ORDER BY ITM_CD),
		D.ITM_NM,
		D.ITM_VALUE
	FROM APR_GAD500 D -- 근태 내역
	WHERE (D.EMP_NO = :EMPNO OR :EMPNO = '')
	AND (D.WORK_MON = :MON OR :MON = '')
	AND D.ITM_VALUE != 0;
	
	CREATE LOCAL TEMPORARY TABLE #TEMP(
		SEQ INT,
		TMP1STR NVARCHAR(20),
		TMP1VAL INT,
		TMP2STR NVARCHAR(20),
		TMP2VAL INT,
		TMP3STR NVARCHAR(20),
		TMP3VAL INT
	);
	
	SELECT
		COUNT(*)
	INTO X
	FROM #TMP1;
	
	SELECt
		COUNT(*)
	INTO Y
	FROM #TMP2;
	
	SELECT
		COUNT(*)
	INTO Z
	FROM #TMP3;
	
	ROWCNT := :X;
	
	IF :ROWCNT < :Y THEN
		ROWCNT := :Y;
	END IF;
	
	IF :ROWCNT < :Z THEN
		ROWCNT := :Z;
	END IF;
	
	I := 1;
	
	WHILE :I <= ROWCNT do
		INSERT INTO #TEMP
		SELECT
			:I,
			A.TMP1STR,
			A.TMP1VAL,
			B.TMP2STR,
			B.TMP2VAL,
			C.TMP3STR,
			C.TMP3VAL
		FROM DUMMY D
		LEFT JOIN #TMP1 A ON :I = A.SEQ
		LEFT JOIN #TMP2 B ON :I = B.SEQ
		LEFT JOIN #TMP3 C ON :I = C.SEQ;
		I := :I + 1;
	END WHILE;

	INSERT INTO #TEMP
	SELECT
		:I AS SEQ,
		'지급 소계' AS TMP1STR,
		SUM(A.TMP1VAL) AS TMP1VAL,
		'공제 소계' AS TMP2STR,
		SUM(B.TMP2VAL) AS TMP2VAL,
		'실수령액' AS TMP3STR,
		(SUM(A.TMP1VAL) - SUM(B.TMP2VAL)) AS TMP3VAL
	FROM #TEMP T
	INNER JOIN #TMP1 A ON T.SEQ = A.SEQ
	INNER JOIN #TMP2 B ON T.SEQ = B.SEQ;

	SELECT * FROM #TEMP;
	DROP TABLE #TMP1;
	DROP TABLE #TMP2;
	DROP TABLE #TMP3;
	DROP TABLE #TEMP;
END;
CALL APR_PAB0901('201902', '17030678');