CREATE PROCEDURE APR_QM_1800_100(
	IN CODE	NVARCHAR(100),
	IN GRP	NVARCHAR(5)
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
	BEGIN
	SELECT
		A.ITEMCODE,
		B."ItemName",
		B."LastPurPrc",
		MAX(CASE WHEN RIGHT(DOCDATE, 2) = '01' THEN A.PRICE END) AS "1월",
		MAX(CASE WHEN RIGHT(DOCDATE, 2) = '02' THEN A.PRICE END) AS "2월",
		MAX(CASE WHEN RIGHT(DOCDATE, 2) = '03' THEN A.PRICE END) AS "3월",
		MAX(CASE WHEN RIGHT(DOCDATE, 2) = '04' THEN A.PRICE END) AS "4월",
		MAX(CASE WHEN RIGHT(DOCDATE, 2) = '05' THEN A.PRICE END) AS "5월",
		MAX(CASE WHEN RIGHT(DOCDATE, 2) = '06' THEN A.PRICE END) AS "6월",
		MAX(CASE WHEN RIGHT(DOCDATE, 2) = '07' THEN A.PRICE END) AS "7월",
		MAX(CASE WHEN RIGHT(DOCDATE, 2) = '08' THEN A.PRICE END) AS "8월",
		MAX(CASE WHEN RIGHT(DOCDATE, 2) = '09' THEN A.PRICE END) AS "9월",
		MAX(CASE WHEN RIGHT(DOCDATE, 2) = '10' THEN A.PRICE END) AS "10월",
		MAX(CASE WHEN RIGHT(DOCDATE, 2) = '11' THEN A.PRICE END) AS "11월",
		MAX(CASE WHEN RIGHT(DOCDATE, 2) = '12' THEN A.PRICE END) AS "12월"
	FROM
	(
		SELECT
			A."ItemCode" AS ITEMCODE,
			TO_NVARCHAR(A."DocDate", 'YYYYMM') AS DOCDATE,
			A."Price" AS PRICE
		FROM OINM A
		INNER JOIN (
			SELECT -- 유효한 월별 마지막 전표의 행(TransNum) 조회
				A."ItemCode" AS ITEMCODE,
				TO_NVARCHAR(A."DocDate", 'YYYYMM') AS DOCDATE,
				MAX(A."TransNum") AS TRANSNUM
			FROM OINM A
			INNER JOIN OPCH B ON A."CreatedBy" = B."DocEntry"
			WHERE A."TransType" = 18
			AND A."Price" > 0
			AND B."CANCELED" = 'N'
			GROUP BY A."ItemCode", A."DocDate"
		) B ON A."ItemCode" = B.ITEMCODE AND A."TransNum" = B.TRANSNUM
	) A
	INNER JOIN OITM B ON A.ITEMCODE = B."ItemCode"
	WHERE A.ITEMCODE = :CODE OR '' = :CODE
	AND B."ItmsGrpCod" = :GRP OR '' = :GRP
	GROUP BY A.ITEMCODE, B."ItemName", B."LastPurPrc"
	ORDER BY A.ITEMCODE;
END;