DROP PROCEDURE APR_PDM_0201R;
CREATE PROCEDURE APR_PDM_0201R
(
	pDocentry	int
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
	SELECT
		TO_NVARCHAR(A."U_POSTDATE", 'YYYY년 MM월 DD일') AS "U_POSTDATE",
		B."LineId",
		B."U_ITEMCODE",
		B."U_ITEMNAME",
		B."U_UNIT",
		B."U_PLANQTY",
		B."U_COMMENT"
	FROM "@APR_OWOR" A
	INNER JOIN "@APR_WOR1" B ON A."DocEntry" = B."DocEntry"
	WHERE B."DocEntry" = :pDocentry
	ORDER BY B."U_PRIORITY";
END;
CALL APR_PDM_0201R(15);