CREATE PROCEDURE APR_OEM0901
(
	IN TRDT NVARCHAR(10),
	IN CARDCODE NVARCHAR(20),
	IN JEJU	NVARCHAR(1)
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
	-- 사골(3) 총3팩 / C304, C306, C315, C316, C319, C320, C323, C325, C327, C328, C330, C333, C334, C338 총14팩 / 뻥16-단호(2), 뻥16-브로(2), 뻥16-블루(2), 뻥16-소고기(4) 총10팩
	-- 쌀눈핫도그(10) 총10팩 / 곤드레(20) 총20팩 / 호, 단 , 팥(2) 총4팩 / 21-딸기, 21-바나나, 21-블루, 21-사과 총4팩 / 배도라지즙(20) 총20팩 / 순수김(10) 총10팩
	-- 10 식혜, 100 컵밥, 110 동결성인죽, 120 과자, 130 배도라지즙, 140 순수김, 20 핫도그, 30 곤드레, 40 (간편하게 비벼먹는 곤드레), 50 쌀눈, 60 사골, 70 성인죽, 80 냉장이유식, 90 실온이유식

	CREATE LOCAL TEMPORARY TABLE #TMPQTY ( -- 송장 가공 테이블
		DOCENTRY	INT,
		ORDERNO		NVARCHAR(30), -- 주문번호
		ORDERDT		NVARCHAR(20), -- 주문일시
		RECEINM		NVARCHAR(100), -- 수취인
		RECPOST		NVARCHAR(100), -- 우편번호
		RECADD		NVARCHAR(100), -- 주소
		RECTEL		NVARCHAR(100), -- 전화번호
		ITEMNAME	NVARCHAR(100), -- 상품명
		PRINTSEQ	INT,
		PRINTED		NVARCHAR(2000), -- 송장출력내용
		SUMQTY		INT, -- 총 @팩
		REQUEST		NVARCHAR(255) -- 배송메세지
	);
	
	INSERT INTO #TMPQTY (
		DOCENTRY,
		ORDERNO,
		ORDERDT,
		RECEINM,
		RECPOST,
		RECADD,
		RECTEL,
		ITEMNAME,
		PRINTSEQ,
		PRINTED,
		SUMQTY,
		REQUEST
	)
	SELECT
		B."DocEntry",
		B."U_ORDERNO",
		TO_NVARCHAR(B."U_ORDERDT", 'YYYYMMDD'),
		B."U_RECEINM",
		B."U_RECPOST",
		B."U_RECADD",
		B."U_RECTEL",
		B."U_ITEMNAME",
		D."U_PRINTED",
		COALESCE(B."U_MESSAGE", '') || STRING_AGG(
			COALESCE(C."FrgnName", '') ||
			CASE
				WHEN TO_INT(B."U_QUANTITY") > 1
				THEN '(' || TO_INT(B."U_QUANTITY") || ')'
				ELSE ''
			END,
			', '
			ORDER BY B."U_ITEMCODE"
		) AS "PRINTED",
		SUM(B."U_QUANTITY"),
		B."U_REQUEST"
	FROM "@APR_OSHP" A
	INNER JOIN "@APR_SHP1" B ON A."DocEntry" = B."DocEntry"
	INNER JOIN OITM C ON B."U_ITEMCODE" = C."ItemCode"
	INNER JOIN "@APR_GRP1" D ON C."U_GROUP1" = D."Code"
	AND TO_NVARCHAR(A."U_DOCDATE", 'YYYYMMDD') = :TRDT
	AND (A."U_CARDCODE" = :CARDCODE OR '' = :CARDCODE)
	GROUP BY B."DocEntry", B."U_ORDERNO", B."U_ORDERDT", B."U_RECEINM", B."U_RECPOST", B."U_RECADD",
		B."U_RECTEL", B."U_ITEMNAME", B."U_REQUEST", B."U_MESSAGE", D."U_PRINTED"
	ORDER BY B."DocEntry", B."U_ORDERNO", D."U_PRINTED";
	
	-- 송장 가공 테이블 조회
	-- 제주도 조회 O - :JEJU = Y
    -- 제주도 조회 X - :JEJU = N
	SELECT
		A."ORDERNO",
		A."ORDERDT",
		A."RECEINM",
		A."RECPOST",
		A."RECADD",
		A."RECTEL",
		A."RECTEL" AS "PHONE",
		A."ITEMNAME",
		STRING_AGG(A."PRINTED" || ' 총' || A."SUMQTY" || '팩', ' / ') AS "PRINTED",
		A."REQUEST"
	FROM #TMPQTY A
	GROUP BY A."ORDERNO", A."ORDERDT", A."RECEINM", A."RECPOST", A."RECADD", A."RECTEL", A."ITEMNAME", A."REQUEST";
	
	DROP TABLE #TMPQTY;
END;