DROP PROCEDURE APR_PDM0101;
CREATE PROCEDURE APR_PDM0101 (
	IN ORDT	NVARCHAR(10)
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
	SELECT
		B."U_ITEMCODE" AS "품목코드",
		C."ItemName" AS "품명",
		SUM(B."U_QUANTITY") AS "주문수량",
		COALESCE(D."PlannedQty", 0) AS "생산예정",
		(SUM(B."U_QUANTITY") - COALESCE(D."PlannedQty", 0)) AS "생산오더수량"
	FROM "@APR_SHOPM1" A
	INNER JOIN "@APR_SHOPM2" B ON A."DocEntry" = B."DocEntry"
	INNER JOIN OITM C ON B."U_ITEMCODE" = C."ItemCode"
	LEFT JOIN (
		SELECT
			V."ItemCode",
			SUM(V."PlannedQty") AS "PlannedQty"
		FROM OWOR V
		WHERE V."Status" NOT IN ('C', 'L')
		AND TO_NVARCHAR(V."PostDate", 'YYYYMMDD') = :ORDT
		GROUP BY V."ItemCode"
	) D ON B."U_ITEMCODE" = D."ItemCode"
	WHERE TO_NVARCHAR(A."U_ORDERDT", 'YYYYMMDD') = :ORDT
	GROUP BY B."U_ITEMCODE", C."ItemName", D."PlannedQty"
	ORDER BY B."U_ITEMCODE";
END;
CALL APR_PDM0101('20190806');