CREATE PROCEDURE APR_OEM0901 (
	IN FR_ORDT	NVARCHAR(10),	-- 주문일 From
	IN TO_ORDT	NVARCHAR(10),	-- 주문일 To
	IN FR_TRDT	NVARCHAR(10),	-- 배송일 From
	IN TO_TRDT	NVARCHAR(10),	-- 배송일 To
	IN CARDCODE	NVARCHAR(20)	-- 거래처코드
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS
BEGIN
	CREATE LOCAL TEMPORARY TABLE #TMPQTY (	-- 주문번호에 따른 개수
		DOCENTRY	INT,
		HORDNO		NVARCHAR(30),
		QTY1		DECIMAL(15,0),
		QTY2		DECIMAL(15,0),
		QTY3		DECIMAL(15,0),
		QTY4		DECIMAL(15,0),
		TOTQTY		DECIMAL(15,0),
		BOXQTY		DECIMAL(15,0)
	);
	
	INSERT INTO #TMPQTY (
		DOCENTRY,
		HORDNO,
		QTY1,
		QTY2,
		QTY3,
		QTY4,
		TOTQTY,
		BOXQTY
	)
	SELECT
		A."DocEntry",
		B."U_ORDERNO",
		SUM(B."U_QUANTITY"),
		0,
		0,
		0,
		SUM(B."U_QUANTITY"),
		1
	FROM "@APR_SHOPM1" A
	INNER JOIN "@APR_SHOPM2" B ON A."DocEntry" = B."DocEntry"
	INNER JOIN OCRD C ON A."U_CARDCODE" = C."CardCode"
	INNER JOIN OITM D ON B."U_ITEMCODE" = D."ItemCode"
	WHERE A."Canceled" = 'N'
	AND ((TO_NVARCHAR(B."U_ORDERDT", 'YYYYMMDD') BETWEEN :FR_ORDT AND :TO_ORDT) OR ('' = :FR_ORDT AND '' = :TO_ORDT))
	AND ((TO_NVARCHAR(B."U_TRANSDT", 'YYYYMMDD') BETWEEN :FR_TRDT AND :TO_TRDT) OR ('' = :FR_TRDT AND '' = :TO_TRDT))
	GROUP BY A."DocEntry", B."U_ORDERNO";
	
	SELECT
		MAX(A."U_CARDNAME") AS "채널명L000Y",
		B."U_ORDERNO" AS "주문번호L000Y",
		MAX(B."U_RECEIVER") AS "아이디L000Y",
		MAX(B."U_RECEINM") AS "이름L000Y",
		MAX(B."U_RECTEL") AS "휴대폰L000Y",
		MAX(B."U_RECADD") AS "주소L000Y",
		MAX(B."U_RECPOST") AS "우편번호L000Y",
		MAX(B."U_ORDTYPE") AS "주문구분L000Y",
		MAX('') AS "제품명L000Y",
		SUM(B."U_QUANTITY") AS "수량R000Y",
		MAX(B."U_REQUEST") AS "요청사항L000Y",
		MAX(B."U_ORDTYPE") || MAX(B."U_ITEMNAME") AS "출력사항L000Y",
		STRING_AGG(B."U_ITEMNAME" || ' ' || TO_INT(B."U_QUANTITY") || '개', '  ') AS "우체국출력사항L000Y",
		MAX(C."TOTQTY") AS "총수량R000Y",
		CASE
			WHEN MAX(C."BOXQTY") = 1
			THEN 'N'
			ELSE 'Y'
		END AS "BOX분리여부L000Y",
		MAX(C."BOXQTY") AS "BOX수량R000Y",
		MAX(C."TOTQTY") AS "이유식환산총수량R000Y",
		MAX('') AS "기준품목L000Y",
		MAX(B."U_TRANTYPE") AS "배송형태L000Y",
		MAX(B."U_INVOICE") AS "결제딜번호L000Y",
		MAX(B."U_ORDTIME") AS "주문시간L000Y",
		MAX(B."U_ITEMCODE") AS "품목코드L000Y",
		MAX(B."U_TRANSDT") AS "배송일L000Y",
		MAX(B."U_PAYTYPE") AS "결제방법L000Y"
	FROM "@APR_SHOPM1" A
	INNER JOIN "@APR_SHOPM2" B ON A."DocEntry" = B."DocEntry"
	INNER JOIN #TMPQTY C ON A."DocEntry" = C."DOCENTRY" AND B."U_ORDERNO" = C."HORDNO"
	INNER JOIN OCRD D ON A."U_CARDCODE" = D."CardCode"
	INNER JOIN OITM E ON B."U_ITEMCODE" = E."ItemCode"
	GROUP BY A."DocEntry", B."U_ORDERNO"
	ORDER BY B."U_ORDERNO";
	
	DROP TABLE #TMPQTY;
END;